config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "games#index"

  resources :games do
    resources :buildings
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :buildings

  validates :title, presence: true
  validates :player, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @building = @game.buildings.create(building_params)
    redirect_to game_path(@game)
  end

  private
    def building_params
      params.expect(building: [ :name, :description, :building_type ])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def game_params
      params.require(:game).permit(:title, :player, :turn_year, :turn_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: game do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% game.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :player %><br>
    <%= form.text_field :player %><br>
    <% game.errors.full_messages_for(:player).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :turn_year %><br>
    <%= form.text_field :turn_year, value:'3000'%><br>
  </div>
  <div>
    <%= form.label :turn_day %><br>
    <%= form.text_field :turn_day %><br>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render "form", game: @game %>

app/views/games/index.html.erb
<h1>Kaiju Big Battle Games</h1>
<ul>
  <% @games.each do |game| %>
  <li>
    <%= link_to game.title, game %>
  </li>
  <% end %>
</ul>

<%= link_to "New Game", new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render "form", game: @game %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>

<p>Player: <%= @game.player %></p>
<p>Year: <%= @game.turn_year %> | Day: <%= @game.turn_day %></p>


<h3>Buildings</h3>
<% @game.buildings.each do |building| %>
  <p>
    <strong>Name:</strong>
    <%= building.name %> | <%= building.building_type %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= building.description %>
  </p>
<% end %>

<ul>
  <li>
    <%= link_to 'Home', root_path %>
  </li>
</ul>

<h3>Debug</h3>
<ul>
  <li><%= link_to "Edit", edit_game_path(@game) %></li>
  <li><%= link_to "Destroy", game_path(@game), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>
<div>
<h3>Add a Building</h3>
<%= form_with model: [ @game, @game.buildings.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :building_type %><br>
    <%= form.text_field :building_type %>
  </p>
  <p>
    <%= form.submit %>
  </p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kaiju" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>